project_name: calma
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/calma/
    binary: calma
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    goos:
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
  - id: calma-linux
    main: ./cmd/calma
    binary: calma
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    goos:
      - linux
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - CREDITS
release:
  prerelease: auto
brews:
  - repository:
      owner: ddddddO
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: 'https://github.com/ddddddO/calma'
    description: '♻Calendar for Markdown♻ ...only for Japan!🎌'
    license: "BSD-2-Clause"
scoops:
  - repository:
      owner: ddddddO\
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/ddddddO/calma/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/ddddddO/calma"
    description: "♻Calendar for Markdown♻ ...only for Japan!🎌"
    license: "BSD-2-Clause"
nfpms:
  - id: calma-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - calma-linux
    homepage: https://github.com/ddddddO/calma
    maintainer: ddddddO <lbfdeatq@gmail.com>
    description: "Calendar for Markdown ...only for Japan!"
    license: BSD-2-Clause
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1