name: ci
on: [push]

jobs:
  test:
    name: test and coverage
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: checkout
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: test
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic -v
